# Generated by Django 6.0.4 on 2026-04-21 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('classification', models.CharField(choices=[('phishing', 'Phishing'), ('legitimate', 'Legitimate')], max_length=20)),
                ('confidence', models.FloatField()),
                ('is_url_scan', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
